DROP TABLE IF EXISTS BOOK;

CREATE TABLE BOOK (
    id INTEGER AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    author VARCHAR(255) NOT NULL,
    price DOUBLE NOT NULL,
    stock BIGINT NOT NULL,
    genre VARCHAR(255)
);
